---
title: "Sta 523 - Homework 6"
author: Walker Harrison, Yunlu Hao, Jae Yeon Lee
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setup

```{r}
# Load any necessary packages here

library(sf)
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(purrr)
library(parallel)
library(xgboost)
```

### Task 1 - Clean and Merge Data

#### Parking Violation Data

```{r message=FALSE}
if (!file.exists("nyc_parking.Rdata")) {
  nyc_raw = read_csv("/data/nyc_parking/NYParkingViolations.csv") 
  
  nyc = nyc_raw %>%
    setNames(str_replace_all(names(.)," ", "_")) %>%
    dplyr::select(Violation_Precinct, House_Number, Street_Name) %>%
    transmute(precinct = Violation_Precinct, address = paste(House_Number, Street_Name)) %>%
    filter(address != "") %>%
    filter(precinct <= 34)
  
  save(nyc, file="nyc_parking.Rdata")
} else {
  load(file="nyc_parking.Rdata")
}
```

#### Geocoding Data

```{r warning=FALSE}
pluto = st_read("/data/nyc_parking/pluto_manhattan/MNMapPLUTO.shp", quiet=TRUE, stringsAsFactors = FALSE)

pluto = pluto %>%
  st_geometry() %>%
  st_centroid() %>%
  st_coordinates() %>% 
  data.frame(address = pluto$Address, ., stringsAsFactors = FALSE) %>%
  tbl_df() %>%
  filter(!is.na(address))
```


#### Clean and merge data

```{r}
nyc$address = 
  toupper(nyc$address) %>%
  str_replace_all(.,"BLVD", "BL") %>% 
  str_replace_all(.,"STREET|(STREE|STRT|STRE|STR)$","ST") %>%
  str_replace_all(., "AVENUE|(AVEN|AVENU|AV)$", "AVE") %>%
  str_replace_all(.,"EAST","E") %>% 
  str_replace_all(., "WEST", "W") %>%
  str_replace_all(.,"SOUTH","S") %>%
  str_replace_all(.,"NORTH","N") %>%
  str_replace_all(., "\\s(DRIVE|DRI|DRIV)$", " DR") %>%
  str_replace_all(.,"\\s(PLACE|PLAC|PLACES)$", " PL") %>%
  str_replace_all(.,"\\s(SQUARE|SQUAR|SQUARES|SQE)$", " SQ") %>%
  str_replace_all(., "AVE OF THE AMER", "6 AVE") %>%
  str_replace_all(., "(?<=\\d)(TH|ST|ND|RD)", "") %>%
  str_replace_all(., "BWAY", "BROADWAY")

#here is to find the pattern like 123 E 123 adding ST at the end 
#also if the pattern like 123 123 adding AVE at the end 

nyc =nyc %>%
  mutate(AVE = str_detect(address,"^[0-9]+\\s[0-9]+$")) %>%
  mutate(ST = str_detect(address,"^[0-9]+\\s(E|W|N|S)\\s?[0-9]+$")) %>%
  mutate(address = ifelse(AVE, paste(address,"AVE"), address))%>%
  mutate(address = ifelse(ST, paste(address,"ST"), address)) %>%
  select(-c(AVE, ST))


pluto$address = 
  toupper(pluto$address) %>% 
  str_replace_all(.,"BLVD", "BL") %>% 
  str_replace_all(.,"STREET","ST") %>%
  str_replace_all(., "AVENUE", "AVE") %>%
  str_replace_all(.,"STREET|(STREE|STRT|STRE|STR)$","ST") %>%
  str_replace_all(.,"AVENUE|(AVEN|AVENU|AV)$", "AVE") %>%
  str_replace_all(.,"EAST","E") %>% 
  str_replace_all(., "WEST", "W") %>%
  str_replace_all(.,"SOUTH","S") %>%
  str_replace_all(.,"NORTH","N") %>%
  str_replace_all(., "\\s(DRIVE|DRI|DRIV|)$", " DR") %>%
  str_replace_all(.,"\\s(PLACE|PLAC|PLACES)$", " PL") %>%
  str_replace_all(.,"\\s(SQUARE|SQUAR|SQUARES|SQE)$", " SQ") %>%
  str_replace_all(., "AVE OF THE AMER", "6 AVE") %>%
  str_replace_all(., "(?<=\\d)(TH|ST|ND|RD)", "") %>%
  str_replace_all(., "BWAY", "BROADWAY")

# here is are some ways to improve that when the nyc has the address like "138 SPRING" make it to "138 SPRING ST"
# however takes toooo long 

ave = pluto$address %>%
  str_extract(., "\\s([A-Z])+\\sAVE") %>%
  str_extract(.,".*\\s")%>%str_trim() %>%
  na.omit() %>%
  unique()

street = pluto$address %>%
  str_extract(., "\\s([A-Z])+\\sST") %>%
  str_extract(.,".*\\s")%>%str_trim() %>%
  na.omit() %>%
  unique()

# nyc = nyc %>%
#   mutate(address = ifelse(word(address, -1) %in% street, paste(address,"ST"), ifelse(word(address, -1) %in% street, paste(address,"AVE"), address)))


d = inner_join(
  nyc,
  pluto,
  by="address"
)

# dis = rep(NA, 22)
# percent = dis
# j = 1
# for(i in manh_precincts) {
#   m = nyc %>%filter(precinct == i)
#   temp = inner_join(
#           m,
#           pluto,
#           by="address"
#         )
#   percent[j] = nrow(temp)/nrow(m)
#   j = j+1
# }

nyc =nyc %>%
  mutate(AVE = str_detect(address,"^[0-9]+\\s[0-9]+$")) %>%
  mutate(ST = str_detect(address,"^[0-9]+\\s(E|W|N|S)\\s?[0-9]+$")) %>%
  mutate(address = ifelse(AVE, paste(address,"AVE"), address))%>%
  mutate(address = ifelse(ST, paste(address,"ST"), address)) %>%
  select(-c(AVE, ST))%>%
  mutate(address = ifelse(word(address, -1) %in% street, paste(address,"ST"), ifelse(word(address, -1) %in% ave, paste(address,"AVE"), address)))



x = nyc %>%filter(precinct == 23)
y = nyc %>%filter(precinct == 25)
z = nyc %>%filter(precinct == 26)

a = inner_join(
  x,
  pluto,
  by="address"
)
b = inner_join(
  y,
  pluto,
  by="address"
)
c = inner_join(
  z,
  pluto,
  by="address"
)

bbb = subset(y, !(y$address %in% b$address))
ccc = subset(z, !(z$address %in% c$address))

aaa = aaa %>%
  mutate(address = ifelse(word(address, -1) %in% street, paste(address,"ST"), ifelse(word(address, -1) %in% ave, paste(address,"AVE"), address)))




manh_precincts = c(1,5,6,7,9,10,13,14,17,18,19,20,22,23,24,25,26,28,30,32,33,34)

d = filter(d, precinct %in% manh_precincts)




```


## Task 2 - Modeling

### Setup

```{r}

if (!file.exists("manh.Rdata")) {
    
  manh = st_read("/data/nyc_parking/nybb/nybb.shp", quiet=TRUE) %>%
    filter(BoroName == "Manhattan")
  
  bbox = st_bbox(manh)
  
  X = seq(bbox["xmin"], bbox["xmax"], 0.00075)
  Y = seq(bbox["ymin"], bbox["ymax"], 0.00075)
  
  grid = expand.grid(X=X, Y=Y) %>% 
    as.matrix() %>%
    st_multipoint() %>%
    st_sfc() %>%
    st_set_crs(st_crs(manh))
      
  manh_pts = st_intersection(st_geometry(manh), grid) %>% st_cast("POINT")
   
  manh_xy = st_coordinates(manh_pts) %>% as.data.frame()
  
  save(manh, manh_pts, manh_xy, file="manh.Rdata")
} else {
  load("manh.Rdata")
}

cp <- st_polygon(list(cbind(c(-73.958188, -73.949227, -73.972994, -73.981783,-73.958188),
                            c(40.800527, 40.796904, 40.764343, 40.768075, 40.800527)))) %>% 
  st_sfc() %>% st_set_crs(st_crs(manh))

cp_pts = data.frame(precinct = 22,
                    address = NA,
                    st_intersection(cp, manh_pts) %>% 
                      st_cast("POINT") %>% st_coordinates())

d = rbind(d, cp_pts)
```

### "Multiple" Logistic Regression

```{r}
if (!file.exists("mlr_pred.Rdata")) {

  d_mlr = d %>% dplyr::select(-address)
  precincts = d_mlr$precinct %>% unique() %>% sort()
  
  
  pb = dplyr::progress_estimated(length(precincts))
  pred = map(
    precincts,
    function(p) {
      pb$tick()$print()
      d_mlr %>%
        mutate(cur_prec = (precinct == p)) %>%
        {suppressWarnings(glm(cur_prec ~ poly(X,2)*poly(Y,2), family=binomial, data=.))} %>%
        predict(newdata=manh_xy, type="response")
    }
  )
  
  pred_index = do.call(cbind, pred) %>%
    apply(1, which.max)

  pred_precinct = precincts[pred_index]
  
  pred_df = cbind(manh_xy, precinct = pred_precinct)
  pred_sf = st_sf(precinct = pred_precinct, geometry = manh_pts)
  
  save(pred_df, pred_sf, file="mlr_pred.Rdata")
} else {
  load("mlr_pred.Rdata")
}
```

```{r}
## Prediction data frame

ggplot(pred_df) +
  geom_point(aes(x=X,y=Y,color=as.factor(precinct)), size=0.1, alpha=0.5) +
  guides(color = guide_legend(override.aes = list(size=2)))
```

```{r}
## Prediction sf

ggplot() +
  geom_sf(data=pred_sf, aes(color=as.factor(precinct)), size=0.1, alpha=0.5) +
  guides(color = guide_legend(override.aes = list(size=2)))
```

```{r}
## Predicting boundaries

pred_sf_mp = pred_sf %>%
  group_by(precinct) %>%
  summarize(geometry = list(st_cast(geometry,"MULTIPOINT")))

pred_boundary = pred_sf_mp %>% st_buffer(0.00075) %>% st_buffer(-0.0006) 
  
  #st_intersection(st_geometry(manh))

# devtools::install_github("tidyverse/ggplot2")
ggplot() +
  geom_sf(data=pred_boundary, aes(fill=as.factor(precinct)), alpha=0.3)
```


```{r}
st_write(pred_boundary, "precincts.geojson", delete_dsn = TRUE, quiet=TRUE)
```


### Multinomial Regression

```{r}
# library(nnet)
# 
# d_mn = d %>% select(-address) %>% mutate(precinct = as.factor(precinct))
# 
# mn = multinom(precinct ~ poly(X,2)*poly(Y,2), data=d_mn)
# 
# precinct_pred = predict(mn, newdata=manh_xy)
# 
# pred_df = cbind(manh_xy, precinct=precinct_pred)
# 
# pred_sf = st_sf(precinct = precinct_pred, geometry = manh_pts)
# 
# ggplot(pred_df) +
#   geom_point(aes(x=X,y=Y,color=precinct_pred), size=0.1, alpha=0.5)
# 
# 
# pred_sf_mp = pred_sf %>%
#   group_by(precinct) %>%
#   summarize(geometry = list(st_cast(geometry,"MULTIPOINT")))
# 
# pred_boundary = pred_sf_mp %>% st_buffer(0.00075) %>% st_buffer(-0.0006) 
#   
#   #st_intersection(st_geometry(manh))
# 
# # devtools::install_github("tidyverse/ggplot2")
# ggplot() +
#   geom_sf(data=pred_boundary, aes(fill=as.factor(precinct)), alpha=0.3)
# 
# st_write(pred_boundary, "precincts.geojson", delete_dsn = TRUE, quiet=TRUE)
```



### xgboost

```{r}
d_xg = d %>% dplyr::select(-address) %>% mutate(precinct = as.factor(precinct))

precincts = d_xg$precinct %>% levels()
y = (d_xg$precinct %>% as.integer()) - 1L
x = d_xg %>% dplyr::select(X,Y) %>% as.matrix()

m = xgboost(data=x, label=y, nthread=4, nround=50, objective="multi:softmax", num_class=length(precincts))

p_index = predict(m, newdata=as.matrix(manh_xy))
precinct_pred = precincts[p_index+1L] %>% as.character() %>% as.integer()

pred_df = cbind(manh_xy, precinct=precinct_pred)

pred_sf = st_sf(precinct = precinct_pred, geometry = manh_pts)


pred_sf_mp = pred_sf %>%
  dplyr::group_by(precinct) %>%
  dplyr::summarize(geometry = list(st_cast(geometry,"MULTIPOINT")))

pred_boundary = pred_sf_mp %>% st_buffer(0.00075) %>% st_buffer(-0.0005)

st_write(pred_boundary, "precincts.geojson", delete_dsn = TRUE, quiet=TRUE)
```